/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-env.d.ts --config dist/server/wrangler.json --include-runtime false --env-interface BgpEnv` (hash: b180adf975465a82ca066d206e64a8b8)
interface __BaseEnv_BgpEnv {
	BGP_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	APP_ORIGIN: "https://bgp.thanejoss.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/server/index");
	}
	interface Env extends __BaseEnv_BgpEnv {}
}
interface BgpEnv extends __BaseEnv_BgpEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN">> {}
}
